spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/onlineFoodDelivery?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: akhil
    password: akhil123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090
