spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql:3306/onlineFoodDelivery
    username: akhil
    password: akhil123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9090

